## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: MIT-0

# Configures remote multi-cluster allocation from cluster-1 to cluster-2
apiVersion: multicluster.agones.dev/v1
kind: GameServerAllocationPolicy
metadata:
  name: allocator-policy-to-cluster-1
  namespace: agones-system
spec:
  connectionInfo:
    allocationEndpoints:
    - ${ALLOCATOR_IP_CLUSTER_1}
    clusterName: "cluster-1"
    namespace: gameservers
    secretName: allocator-secret-to-cluster-1
  priority: 1
  weight: 100